name: Dependencies Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 2'

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Validate
        env:
          LIBQUICKJSC_TEST_PATH: ${{ github.workspace }}/test/assets/libquickjs_c_bridge_plugin.so
        uses: peiffer-innovations/actions-flutter-validate@v2
        with:
          generate_code: true
      - name: Dependencies
        uses: peiffer-innovations/actions-dart-dependency-updater@v1
        with:
          merge: true
          paths: .,example
          pull_request: true
          token: ${{ secrets.REPO_TOKEN }}
